### ISSUE TITLE
How to build on Windows with MinGW compiler?

### ISSUE THREAD

**Issue by iahunq2** [annacrombie/muon#37]
I'm using the MinGW compiler from winlibs.com. `bootstrap.bat` only supports MSVC. I can compile a `muon-bootstrap.exe` with the MinGW compiler but I don't know what to do next.

**Comment by vtorri** [comment]
you can use [MSYS2](https://www.msys2.org), that's what I do to compile on Windows. It offers several toolchains (mingw32, mingw64, clang one, UCRT, etc...). Then in one of the terminals, you run the following commands (or you save them in a shell script):

```
CC="gcc" CFLAGS="-g3 -ggdb3 -std=c99" ./bootstrap.sh build
CC="gcc" CFLAGS="-g3 -ggdb3 -std=c99" ./build/muon.exe setup build_muon
ninja -C build_muon/
```
then, muon.exe will be in `build_muon/` subdirectory

**Comment by iahunq2** [comment]
Thank you. I managed to do it without MSYS2. It's easier than I think.
