### ISSUE TITLE
How to build code using the built-in samu?

### ISSUE THREAD

**Issue by iahunq2** [annacrombie/muon#44]
I always use a standalone ninja up to now. I found that samu is embedded into the muon executable itself. But the equivalent command to meson, `muon compile -C build`, doesn't work (see: #43). Since there is no standalone samu executable and there is also no way to start the build via muon itself, how could I use the built-in samu?

Update: Maybe the syntax is `muon -C build [something]` based on the commands on Stage 2? But how to know what this [something] is? Take this project for example: https://github.com/franko/fox. I have tried everything I could think of but it always said `err invalid command [something]`!

**Comment by ma8ma** [comment]
Hi @iahunq2 

Try `muon samu -C build` instead of `muon compile -C build`.

**Comment by iahunq2** [comment]
> Hi @iahunq2
> 
> Try `muon samu -C build` instead of `muon compile -C build`.

Take this project for example: https://github.com/franko/fox

According to you, the command will be `muon [something] -C build`. But how to know what this [something] is?
