### ISSUE TITLE
muon can't build libsigcplusplus

### ISSUE THREAD

**Issue by iahun2** [annacrombie/muon#49]
https://github.com/libsigcplusplus/libsigcplusplus

Error message:

```
C:/Work/libsigcplusplus/meson.build:76:65: error unexpected character: '\'
 76 | is_dist_check = project_source_root.contains('dist-unpack') and \
                                                                      ^
C:/Work/libsigcplusplus/meson.build:77:67: error expected expression, got end of line
 77 |                 project_build_root.contains('dist-build')
                                                                        ^
C:/Work/libsigcplusplus/meson.build:81:52: error unexpected character: '\'
 81 | maintainer_mode = maintainer_mode_opt == 'true' or \
                                                         ^
C:/Work/libsigcplusplus/meson.build:82:54: error expected expression, got end of line
 82 |                  (maintainer_mode_opt == 'if-git-build' and is_git_build)
                                                           ^
C:/Work/libsigcplusplus/meson.build:84:54: error unexpected character: '\'
 84 |   message('Looks like a tarball is being tested. ' + \
                                                           ^
C:/Work/libsigcplusplus/meson.build:99:60: error unexpected character: '\'
 99 | build_documentation = build_documentation_opt == 'true' or \
                                                                 ^
C:/Work/libsigcplusplus/meson.build:100:62: error expected expression, got end of line
100 |                      (build_documentation_opt == 'if-maintainer-mode' and maintainer_mode)
                                                                   ^
C:/Work/libsigcplusplus/meson.build:124:66: error unexpected character: '\'
124 |   assert(cpp_compiler.version().split('.')[0].to_int() >= 19 and \
                                                                       ^
C:/Work/libsigcplusplus/meson.build:146:53: error unexpected character: '\'
146 |   message('The \'dot\' command is not found.\n  ' + \
                                                          ^
C:/Work/libsigcplusplus/meson.build:163:48: error unexpected character: '\'
163 |   warning('Missing files in untracked/.\n  ' + \
                                                     ^
C:/Work/libsigcplusplus/meson.build:369:70: error unexpected character: '\'
369 |   '       Compiler warnings: @0@ (warning_level: @1@, werror: @2@)'. \
                                                                           ^
```

**Comment by vtorri** [comment]
ask the maintainer to remove the backslashes, they are useless. He should read meson doc about backslashes.

**Comment by iahun2** [comment]
> ask the maintainer to remove the backslashes, they are useless. He should read meson doc about backslashes.

Let me tag him for you. Because, like you, I don't know where else to contact him. Btw, why don't you tag him already? Who tags him doesn't really matter. Because most of the time, he doesn't care and ignores the issue.

**Comment by iahun2** [comment]
@annacrombie

**Comment by iahun2** [comment]
> ask the maintainer to remove the backslashes, they are useless. He should read meson doc about backslashes.

Thank you. But that's not an option. Btw, I'm sorry because I misunderstood you comment. I mistake the maintainer you mentioned to be muon's maintainer, not libsigcplusplus's maintainer. I'm really tired waiting for muon's maintainer and sometimes I wonder why I'm wasting time with this project.

**Comment by eli-schwartz** [comment]
I am quite confused by this bug report for two reasons:

- backslashes are a perfectly ordinary part of the meson grammar, and not incorrect to use
- muon supports this just fine. The project successfully configures for me with muon.

**Comment by iahun2** [comment]
> I am quite confused by this bug report for two reasons:
> 
> * backslashes are a perfectly ordinary part of the meson grammar, and not incorrect to use
> * muon supports this just fine. The project successfully configures for me with muon.

Are you using Linux or a POSIX environment on Windows like Cygwin/MSYS2? I'm using pure Win32 with Windows CMD.

**Comment by eli-schwartz** [comment]
> Are you using Linux or a POSIX environment on Windows like Cygwin/MSYS2? I'm using pure Win32 with Windows CMD.

I am using Linux.

So then let's reword this: it is a perfectly ordinary part of the meson grammar, and muon is *supposed* to support it just fine so if it is failing to do so, it is a bug in the work-in-progress Windows support.

**Comment by iahun2** [comment]
Windows support is WIP? Are you confused with @vtorri's WIP windows module?

Why doesn't the muon's maintainer put this on the project's README.md? I've really wasted my time!
