### ISSUE TITLE
muon can't build libasync's tests

### ISSUE THREAD

**Issue by iahun2** [annacrombie/muon#50]
https://github.com/managarm/libasync

Remember to enable build_tests.

I'm using llvm-mingw latest release. The compiler definitely supports -fcoroutines.

**Comment by vtorri** [comment]
more error output would be nice

**Comment by iahun2** [comment]
> more error output would be nice

No. I have pointed the problem to you. But you don't even want to have a look at the project's build script.

Here it is:

https://github.com/managarm/libasync/blob/b8b8cdae95b661ec5c43575be7e2f0110c45c752/tests/meson.build

The problematic code is from line 4 to line 11. Long story short, `meson.get_compiler('cpp').has_argument('-fcoroutines')` returned false even though the compiler supported -fcoroutines.

**Comment by vtorri** [comment]
do you htink that i will download all the projects each there is a bug ? It's you who should give more output. I'm not the mantainer, i just contribute sometimes to muon. So I suggest that you wait for the maintainer to answer.

**Comment by iahun2** [comment]
> do you htink that i will download all the projects each there is a bug ? It's you who should give more output. I'm not the mantainer, i just contribute sometimes to muon. So I suggest that you wait for the maintainer to answer.

As I remember, I didn't tag you. If you don't want to be serious on it, don't comment!
