### ISSUE TITLE
i18n broken in current HEAD (`3433df0`)

### ISSUE THREAD

**Issue by Kangie** [annacrombie/muon#75]
Attempting to make FVWM3's new `meson` build path work  with `muon`, encountered the following error:

```
modules/i18n.meson:176:20: error file '/data/development/temp/fvwm3/po/ar da de fr sv_SE zh_CN ru es.po' does not exist
176 |             input: [current_source_dir / f'@lang@.po'],
                         ^
modules/i18n.meson:173:22: error in function custom_target
173 | /         gmo_target = custom_target(
174 | |             f'@package_name@-@lang@.mo',
175 | |             command: [msgfmt, '-o', '@OUTPUT@', '@INPUT@'],
176 | |             input: [current_source_dir / f'@lang@.po'],
177 | |             output: [
178 | |                 meson.current_build_dir() / lang / 'LC_MESSAGES' / f'@package_name@.mo',
179 | |             ],
180 | |             install: install,
181 | |             install_dir: install_dir / lang / 'LC_MESSAGES',
182 | |             install_tag: 'i18n',
183 | |         )
      |_________^
```

From the following `meson.build` content in [this dir](https://github.com/fvwmorg/fvwm3/blob/6acc82cf99ea64a4d3aeb0efc594d51a9b63d34c/po/).

```meson
i18n = import('i18n')
add_project_arguments('-DGETTEXT_PACKAGE="intltest"', language: 'c')
i18n.gettext(meson.project_name())
i18n.gettext('FvwmScript')
```

I think that we're feeding an array into a variable that expects a string?

**Comment by kzc** [comment]
I don't know anything about i18n standards and conventions, but  muon's `read_linguas` assumes one language per line:

https://github.com/muon-build/muon/blob/3433df0b5b651a6953dae7a99bc92795b13982a8/src/script/modules/i18n.meson#L40-L60

https://github.com/fvwmorg/fvwm3/blob/6acc82cf99ea64a4d3aeb0efc594d51a9b63d34c/po/LINGUAS  contains all languages on a single line.

So either muon's `read_linguas` has to be tweaked to handle multiple languages per line, or change fvwm3's LINGUAS to only have a single language per line.

**Comment by kzc** [comment]
fwiw, meson splits the LINGUAS language tokens per line:

https://github.com/mesonbuild/meson/blob/2b80d4cca174916a4b6d0c47c54ad56795741bb6/mesonbuild/scripts/gettext.py#L34

**Comment by eli-schwartz** [comment]
https://www.gnu.org/software/gettext/manual/html_node/po_002fLINGUAS.html

> The `po/` directory should also receive a file named `LINGUAS`. This file contains the list of available translations. It is a whitespace separated list. Hash-marked comments and white lines are ignored. Here is an example file:

**Comment by eli-schwartz** [comment]
Meson made the same fix in https://github.com/mesonbuild/meson/pull/1131

**Comment by amcn** [comment]
@eli-schwartz is right: meson's implementation is correct, muon's is not. Apologies for not having spotted this during the implementation.

I've pushed a PR which fixes this error. It should allow muon to get further but not quite over the finish line when configuring FVVM3

Looking into the next error, which seems related to manner in which `bin/fvwm-menu-directory.in` is parsed as configure file.
